# Generated by Django 4.0.1 on 2022-01-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.TextField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
